import type { ToolConfig, ToolDescription } from '@codellm/core';

export const vectorDbCollectionName = 'codeSummary' as const;

export const numResults = 8;

export const DEFAULT_CONFIG: ToolConfig = {
  exclude: [
    '**/node_modules/**',
    '**/cdk.out/**',
    '**/coverage/**',
    '**/dist/**',
  ],
  include: [
    '**/*.ts',
    '**/*.js',
    '**/*.jsx',
    '**/*.tsx',
    '**/*.py',
    '**/*.tf',
    '**/*.rb',
    '**/*.java',
    '**/*.c',
    '**/*.cpp',
    '**/*.h',
    '**/*.hpp',
    '**/*.cs',
    '**/*.go',
    '**/*.rs',
    '**/*.swift',
    '**/*.php',
    '**/*.sh',
    '**/*.bash',
    '**/*.fish',
    '**/*.ps1',
    '**/*.psm1',
    '**/*.psd1',
    '**/*.bat',
    '**/*.cmd',
    '**/*.vbs',
    '**/*.vba',
    '**/*.vbscript',
    '**/*.wsf',
    '**/*.wsc',
    '**/*.wsh',
  ],
  vectorDbCollectionName,
  vectorDbName: 'chromadb',
} as const;

export const summarizeTaskPrompt = `
  Your task is to generate an extremely concise summary with minimal prose of the following code file. Keep your summary to 5 sentences or less. Include in your summary:
    - The filename with the path relevant to the project root
    - Dependencies
    - Important functions, classes, and types
    - Relevant information from comments and docs
    - The language used
    - The framework used if you can determine it reliably, if not, do not mention a framework
`;

export const description: ToolDescription = {
  description: `This tool processes a query generated by an LLM to gather relevant code, full file paths, and code summaries from a vector db collection to provide context to assist the asking LLM in answering a question. It can summarize code and provide relevant code to the asker so that it can answer a question. The query should only include relevant functions, classes, types, and concepts that are relevant to the user's question. The information returned should not be considered comprehensive or precise. This tool is a good starting point for discovering information related to a user's question.`,
  name: 'codeSummaryQuery',
  params: [
    {
      description: `A flag to determine if relevant code should be included in the response to help you answer the user's question.`,
      name: 'includeCode',
      required: true,
      type: 'bool',
    },
    {
      description: `The query to use to find relevant code and code summaries to help you answer the user's question. The query should be concise and include functions, classes, or files from within the codebase.`,
      name: 'query',
      required: true,
      type: 'string',
    },
  ],
} as const;
